### ISSUE TITLE
SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing

### ISSUE THREAD

**Issue by RickardPettersson** [FeroxRev/Pokemon-Go-Rocket-API#103]
I have debuging my web project i building on my computer without any problems but now when i deploying it to Amazon Elastic Beanstalk and login in i getting this:

```
`Google.Protobuf.InvalidProtocolBufferException: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
   at Google.Protobuf.CodedInputStream.SkipLastField()
   at POGOProtos.Networking.Envelopes.ResponseEnvelope.MergeFrom(CodedInputStream input)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.
```

Any ideas why i getting this, when i google it its not so many that got this problem.

**Comment by ahmed007boss** [comment]
The same issue when i debug on virtual machine on Microsoft azure

**Comment by RickardPettersson** [comment]
Damit now i got it on my own server also....

**Comment by monoxacc** [comment]
same here, fix needed :/

**Comment by monoxacc** [comment]
Niantic appears to be specifically blocking the AWS port range.
By debugging some HTTP Requests i get following data from stream every time:
`...<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1>...`
€dit: No chance. AWS servers are blacklisted:
https://github.com/PokemonGoMap/PokemonGo-Map/wiki/HTTP-403-Forbidden-Error
