### ISSUE TITLE
Gradlew Problem

### ISSUE THREAD

**Issue by yagoernandes** [FeroxRev/Pokemon-Go-Rocket-API#154]
Hi! I have found some issues while compiling the build using gradlew.bat
- Exception is:
  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':library:compileJava'.
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(Execute
  ActionsTaskExecuter.java:69)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActions
  TaskExecuter.java:46)
      at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExe
  cutionAnalysisTaskExecuter.java:35)
      at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTask
  Executer.java:66)
      at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExec
  uter.java:58)
      at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmpt
  ySourceFilesTaskExecuter.java:52)
      at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWit
  hNoActionsExecuter.java:52)
      at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExec
  uter.java:53)
      at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMo
  stOnceTaskExecuter.java:43)
      at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(Def
  aultTaskGraphExecuter.java:203)
      at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(Def
  aultTaskGraphExecuter.java:185)
      at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(Ab
  stractTaskPlanExecutor.java:66)
      at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTa
  skPlanExecutor.java:50)
      at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.ja
  va:25)
      at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.
  java:110)
      at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java
  :37)
      at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
      at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
      at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
      at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:3
  2)
      at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
      at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
      at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
      at org.gradle.internal.Factories$1.create(Factories.java:22)
      at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecu
  tor.java:91)
      at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecu
  tor.java:53)
      at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:
  150)
      at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
  
  ```
  at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
  at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecu
  ```
  
  tor.java:91)
      at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecu
  tor.java:63)
      at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
      at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProces
  sBuildActionExecuter.java:99)
      at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunne
  r.java:28)
      at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
  
  ```
  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecute
  ```
  
  r.java:48)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecute
  r.java:30)
      at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecu
  ter.java:81)
      at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecu
  ter.java:46)
      at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSugg
  estingBuildActionExecuter.java:51)
      at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSugg
  estingBuildActionExecuter.java:28)
      at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
      at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineA
  ctionFactory.java:239)
      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineA
  ctionFactory.java:212)
      at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.j
  ava:35)
      at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.j
  ava:24)
      at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33
  )
      at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22
  )
      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFac
  tory.java:205)
      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFac
  tory.java:169)
      at org.gradle.launcher.Main.doAction(Main.java:33)
      at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
      at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
      at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
      at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
      at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
      at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
      at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see
  the compiler error output for details.
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:48)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(Nor
  malizingJavaCompiler.java:104)
      at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaComp
  iler.java:53)
      at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaComp
  iler.java:38)
      at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCom
  pilerSupport.java:35)
      at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCom
  pilerSupport.java:25)
      at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:163)
      at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:145)
      at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
      at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
      at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTa
  skAction.doExecute(AnnotationProcessingTaskFactory.java:245)
      at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskA
  ction.execute(AnnotationProcessingTaskFactory.java:221)
      at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTa
  skAction.execute(AnnotationProcessingTaskFactory.java:232)
      at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskA
  ction.execute(AnnotationProcessingTaskFactory.java:210)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteA
  ctionsTaskExecuter.java:80)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(Execute
  ActionsTaskExecuter.java:61)
      ... 60 more

BUILD FAILED

Total time: 18.041 secs

Whats going on??

**Comment by itsff** [comment]
Are you sure you're looking at the right project? This one's written in C# and does not use Java nor gradle...

**Comment by EizoSik** [comment]
Here's a stable working version http://sh.st/VoHDh (1.0.9.6)
