### ISSUE TITLE
Object reference not set to instance of object

### ISSUE THREAD

**Issue by balloman** [FeroxRev/Pokemon-Go-Rocket-API#155]
I get this when running
`at DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformAuthRequest(Dictionary`2 data)
   at DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformMasterLogin(String service, String deviceCountry, String operatorCountry, String lang, Int32 sdkVersion)
   at PokemonGo.RocketAPI.Login.GoogleLogin.<GetAccessToken>d__3.MoveNext() in C:\Users----\OneDrive\Documents\Programming\Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\Users\-----\OneDrive\Documents\Programming\Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI\Rpc\Login.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at BattleTime.Exec.<MainAsync>d__2.MoveNext() in C:\Users\-----\OneDrive\Documents\Programming\Pokemon-Go-Rocket-API-master\BattleTime\Exec.cs:line 54`

Any idea why I get this?

**Comment by balloman** [comment]
DOES NOBODY ANSWER ISSUES?!
