### ISSUE TITLE
Please help.. --- End of inner exception stack trace ---

### ISSUE THREAD

**Issue by LiamRourke** [FeroxRev/Pokemon-Go-Rocket-API#167]
Can somebody please help me
--- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\
Users\Liam\Desktop\Pokemon new\Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI\
Helpers\RetryHandler.cs:line 29

**Comment by dreadylein** [comment]
Please dump Http Request and Responses

**Comment by salvaracer** [comment]
Try to restart, start again worked for me 8-)
