### ISSUE TITLE
System.NullReferenceException caught

### ISSUE THREAD

**Issue by navidemad** [FeroxRev/Pokemon-Go-Rocket-API#216]
I guess the following caused the problem:

**`if (encounterPokemonResponse?.CaptureProbability.CaptureProbability_.First() < 0.4)`**

Log:
```
[11:16:58] Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteCatchAllNearbyPokemons>d__7.MoveNext() in C:\Users\lqmbdq\Documents\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI.Logic\Logic.cs: line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__6.MoveNext() in C:\Users\lqmbdq\Documents\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI.Logic\Logi
c.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<<Execute>b__4_0>d.MoveNext() in C:\Users\lqmbdq\Documents\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI.Logic\Logic.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<RepeatAction>d__5.MoveNext() in C:\Users\lqmbdq\Documents\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI.Logic\Logic.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__4.MoveNext() in C:\Users\lqmbdq\Documents\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI.Logic\Logic.cs:line 44
```

**Comment by J-Saas** [comment]
I can report the exact same error:
http://i.imgur.com/jgBkkes.png

Continues on and works fine even after a reboot regardless.

**Comment by FeroxRev** [comment]
Fixed
