### ISSUE TITLE
Protobuf error when calling ExecuteCatchAllNearbyPokemons()

### ISSUE THREAD

**Issue by RickDB** [FeroxRev/Pokemon-Go-Rocket-API#3]
Tried the console version which works well and report my token / user info only a key function seems broken, using PTC auth and it works up until ExecuteCatchAllNearbyPokemons() : 

Stack trace:
```
Unhandled Exception: Google.Protobuf.InvalidProtocolBufferException: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
   at Google.Protobuf.CodedInputStream.SkipLastField()
   at PokemonGo.RocketAPI.GeneratedCode.PlayerUpdateResponse.MergeFrom(CodedInputStream input) in C:\Users\<user>\Documents\Visual Studio 2015\Projects\Pokemon-Go-Rocket-API\PokemonGo\RocketAPI\GeneratedCode\PlayerUpdateResponse.cs:line 177
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__0`2.MoveNext() in C:\Users\<user>\Documents\Visual Studio 2015\Projects\Pokemon-Go-Rocket-API\PokemonGo\RocketAPI\Extensions\HttpClientExtensions.cs:line 25
```
https://github.com/FeroxRev/Pokemon-Go-Rocket-API/blob/master/PokemonGo/RocketAPI/Console/Program.cs#L53

Haven't tried with Google auth yet but it looks like the returned stream is invalid, would be great if  this can be fixed :+1:

**Comment by FeroxRev** [comment]
Check last commit, new type of server hickup is now being handled

**Comment by RickDB** [comment]
Thanks just missed that one, will re-test :)

**Comment by RickDB** [comment]
With the current version it returns an error during client.LoginPtc() (http 302 error code), maybe servers overloaded but it does crash on that:

```
Unhandled Exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 302 (Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\Users\<user>\Documents\Visual Studio 2015\Projects\Pokemon-Go-Rocket-API\PokemonGo\RocketAPI\Helpers\RetryHandler.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\Users\<user>\Documents\Visual Studio 2015\Projects\Pokemon-Go-Rocket-API\PokemonGo\RocketAPI\Helpers\RetryHandler.cs:line 38
```

**Comment by FeroxRev** [comment]
Ah, the fix was too fast :) Didnt test PTC login. Thank you, fixing now

**Comment by FeroxRev** [comment]
Try again please

**Comment by Martiveen** [comment]
Works for me now!

**Comment by RickDB** [comment]
No error so far, nothing farmed yet but will let it run for a while.

**Comment by FeroxRev** [comment]
It starts farming immediately. Only does 1 run across all nearby pokestops and pokemons, so after a run you will have to restart (or put the stuff in while loop). Did you update the lon/lat in Settings.cs?

**Comment by RickDB** [comment]
Yep correct lon/lat and also tried specifying them directly to the client, added some more logging to the console app and it does report pokestops however not farming so far:

https://gist.github.com/RickDB/f67d4d2c2faf7951d17bcc4c257228f2
