### ISSUE TITLE
GoogleLogin.GetDeviceCode returns empty code

### ISSUE THREAD

**Issue by AR1ES** [FeroxRev/Pokemon-Go-Rocket-API#52]
Response from google: 401 - unauthorized.
Body: {"error": "invalid_client"}

**Comment by ghost** [comment]
Have you tried using your own api credentials? I'm guessing there is a suspension on these hard coded credentials.

**Comment by JoeTheBlow** [comment]
I tried to create a new client ID and client secret but the bot just throws an error anyways and still doesn't work.

**Comment by Kagelol** [comment]
Im guessing we need to enter a good redirect url in the client thingy 

>  A web application is accessed by web browsers over a network.
> 
> Applications that use JavaScript to access Google APIs must specify authorized JavaScript origins. The origins identify the domains from which your application can send API requests.
> Applications that use languages and frameworks like PHP, Java, Python, Ruby, and .NET must specify authorized redirect URIs. The redirect URIs are the endpoints to which the OAuth 2.0 server can send responses.

**Comment by JoeTheBlow** [comment]
Yeah but I wouldn't know what the redirect url should be in the new client ID

**Comment by marcospic** [comment]
I have the same issue. It seems that there is no return.
deviceCode.user_code seems to be null.

[11:12:57] Google Device Code copied to clipboard
Unhandled exception: System.ArgumentNullException: Value cannot be null.
Parameter name: text
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Forms.Clipboard.SetText(String text)
   at PokemonGo.RocketAPI.Login.GoogleLogin.<>c__DisplayClass6_0.<GetDeviceCode>b__0() in D:\vvvvv\Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 63
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Press any key to continue . . .

**Comment by MrDark** [comment]
I tried adding my own OAuth credentials but then it throws an AccessTokenExpiredException in Rpc.Login.SetServer. The server reponse gives StatusCode 102.

**Comment by Afraidium** [comment]
Response viewed through Fiddler

`{
  "error" : "invalid_client"
}`

Maybe we need to use the Client agent specified from the android app? 
("User-Agent", "Niantic App") <- Still valid?

**Comment by anantadwi13** [comment]
update the oauth2 client please...

**Comment by Ar1i** [comment]
Fix comes in the next minutes. Its cause Google Updated some stuff.

**Comment by FeroxRev** [comment]
Got it fixed locally, will push later

**Comment by anantadwi13** [comment]
push now please

**Comment by AR1ES** [comment]
@FeroxRev can you briefly describe the solution?

**Comment by anantadwi13** [comment]
@FeroxRev @AR1ES  yeah, describe how to fix it will be helpful for us

**Comment by Kagelol** [comment]
@anantax13 Perhaps just be patient, most people have better stuff to do all day then to help impatient bot users. Maybe learn to fix ir yourself if it has such a rush

**Comment by FeroxRev** [comment]
Pushed
