### ISSUE TITLE
Servers or?

### ISSUE THREAD

**Issue by Ricktza** [FeroxRev/Pokemon-Go-Rocket-API#63]
Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`2.MoveNext()

PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() in Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 30

at PokemonGo.RocketAPI.Rpc.Map.<GetMapObjects>d__1.MoveNext() in Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI\Rpc\Map.cs:line 69

and many more.

**Comment by ghost** [comment]
Same issue, think its just all these commits that people aren't checking for actual run time errors but we will see.

**Comment by ghost** [comment]
Servers are down apparently

**Comment by FeroxRev** [comment]
This means bad response from servers, you might have annoyed the server
