### ISSUE TITLE
Latest version consistently spammed error

### ISSUE THREAD

**Issue by ghost** [FeroxRev/Pokemon-Go-Rocket-API#64]
[23:51:51] PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`2.MoveNext() in C:\Users\Zachary\Desktop\Necro\trunk\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__6`2.MoveNext() in C:\Users\Zachary\Desktop\Necro\trunk\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Download.<GetItemTemplates>d__2.MoveNext() in C:\Users\Zachary\Desktop\Necro\trunk\FeroxRev\PokemonGo.RocketAPI\Rpc\Download.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Inventory.<GetPokemonSettings>d__20.MoveNext() in C:\Users\Zachary\Desktop\Necro\trunk\PoGo.NecroBot.Logic\Inventory.cs:line 259
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.TransferDuplicatePokemonTask.<Execute>d__0.MoveNext() in C:\Users\Zachary\Desktop\Necro\trunk\PoGo.NecroBot.Logic\Tasks\TransferDuplicatePokemonTask.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\Zachary\Desktop\Necro\trunk\PoGo.NecroBot.Logic\State\FarmState.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__4.MoveNext() in C:\Users\Zachary\Desktop\Necro\trunk\PoGo.NecroBot.Logic\State\StateMachine.cs:line 34

Doesn't run, just loops continuously getting this error.

**Comment by vmcall** [comment]
It's cause the servers are down jesus christ

**Comment by ghost** [comment]
Not on my end they aren't, they are working fine.

**Comment by vmcall** [comment]
"InvalidResponseException" is what happens when you get a 503...
debug it...

**Comment by wouter-heerwegh** [comment]
http://ispokemongodownornot.com/
servers are up and i can login  on my phone, it sometimes loots a pokestop and stuff bit constant error

**Comment by ghost** [comment]
Carl get ur balls out of a twist, if you login via normal client it works fine and catches and pokestops/gyms work fine. It was a mistake on my end.

**Comment by FeroxRev** [comment]
Stop harming the servers and they will treat your bot well

**Comment by wouter-heerwegh** [comment]
I've stopped my bot, necro says it's an api change? Do you know more Ferox?
