### ISSUE TITLE
bug (stop working) 

### ISSUE THREAD

**Issue by muyochy** [FeroxRev/Pokemon-Go-Rocket-API#76]
![bug](https://cloud.githubusercontent.com/assets/20503653/16993370/0ec90e5e-4e71-11e6-88c3-fa947967ff08.jpg)

That happens when you have 10 minutes with the bot running

**Comment by martin-podlubny** [comment]
I can confirm I have the same issue. Not sure about the 10 minute mark, but yeah I eventually get the same.

**Comment by Spegeli** [comment]
Can confirm this too:
```
Unbehandelte Ausnahme: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei PokemonGo.RocketAPI.Console.Program.<ExecuteCatchAllNearbyPokemons>d__4.MoveNext() in E:\Pokemon GO\Pokemon-Go-Rocket-API\FeroxRev\PokemonGo\RocketAPI\Console\Program.cs:Zeile 126.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei PokemonGo.RocketAPI.Console.Program.<ExecuteFarmingPokestopsAndPokemons>d__3.MoveNext() in E:\Pokemon GO\Pokemon-Go-Rocket-API\FeroxRev\PokemonGo\RocketAPI\Console\Program.cs:Zeile 91.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei PokemonGo.RocketAPI.Console.Program.<Execute>d__2.MoveNext() in E:\Pokemon GO\Pokemon-Go-Rocket-API\FeroxRev\PokemonGo\RocketAPI\Console\Program.cs:Zeile 80.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   bei System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bei System.Threading.ThreadPoolWorkQueue.Dispatch()
   bei System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by davidmateos94** [comment]
I had the same after 17 minutes

**Comment by davidmateos94** [comment]
`Unhandled Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at Google.Protobuf.Collections.RepeatedField`1.get_Item(Int32 index)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`2.MoveNext() in C:\Users\David\Desktop\Pokemon-Go-Rocket-API-master\PokemonGo\RocketAPI\Extensions\HttpClientExtensions.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<UpdatePlayerLocation>d__12.MoveNext() in C:\Users\David\Desktop\Pokemon-Go-Rocket-API-master\PokemonGo\RocketAPI\Client.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Console.Program.<ExecuteFarmingPokestopsAndPokemons>d__3.MoveNext() in C:\Users\David\Desktop\Pokemon-Go-Rocket-API-master\PokemonGo\RocketAPI\Console\Program.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Console.Program.<Execute>d__2.MoveNext() in C:\Users\David\Desktop\Pokemon-Go-Rocket-API-master\PokemonGo\RocketAPI\Console\Program.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Press any key to continue . . .

30 minutes now`

**Comment by tw88** [comment]
Same here, after about 5-10min

**Comment by FeroxRev** [comment]
Please dump the request/response you get when receiving this exception (using charles).

**Comment by MSAlih1** [comment]
if you use try-catch for ExecuteCatchAllNearbyPokemons and ExecutePokemonSpawnPoint, program will work

**Comment by youngsemicolon** [comment]
Same problem here
