### ISSUE TITLE
Autosniper

### ISSUE THREAD

**Issue by VisualBoyAdv** [FeroxRev/Pokemon-Go-Rocket-API#87]
when i run it shows this

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PokeSniper2.Program.<>c__DisplayClass9_0.<<Automatic>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by FeroxRev** [comment]
Unrelated to this project
